"""Hatch build hook: stamp the wheel with the git short SHA.

Writes ``src/bonsai_cc/_build_info.py`` before the wheel is packaged,
so the installed copy carries the exact revision it was built from.
``bonsai-cc doctor`` surfaces this — a stale ``uv tool install`` will
show a SHA that mismatches ``git rev-parse --short HEAD`` in the
source tree, which is the failure mode DESIGN.md §14.5 documents.

Rules:

* Git available + repo present: stamp with ``git describe --always
  --dirty --abbrev=7``. ``-dirty`` suffix means the build was made
  against a working tree that differed from HEAD.
* Git not available (building from an unpacked sdist, no .git
  directory): preserve any ``_build_info.py`` that the sdist already
  carries; if there isn't one, fall back to ``"unknown"``.

The generated file is gitignored — it's a build artifact, not source.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class BuildInfoHook(BuildHookInterface):
    PLUGIN_NAME = "build-info"

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        target = Path(self.root) / "src" / "bonsai_cc" / "_build_info.py"
        rev = _git_describe(self.root)
        if rev is None:
            # No git: building from a tarball. Keep any pre-baked
            # value (sdist would have stamped one in); only write
            # the fallback if nothing's there.
            if target.exists():
                return
            rev = "unknown"
        target.write_text(
            '"""Generated by hatch_build.py at build time. Do not edit."""\n'
            f"GIT_REV = {rev!r}\n",
            encoding="utf-8",
        )


def _git_describe(root: str) -> str | None:
    """Return ``git describe --always --dirty --abbrev=7`` or None.

    Returns None if git isn't on PATH or the directory isn't a repo.
    Never raises — a build must not fail because of a missing git.
    """
    try:
        out = subprocess.check_output(
            ["git", "describe", "--always", "--dirty", "--abbrev=7"],
            cwd=root,
            stderr=subprocess.DEVNULL,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return out.strip() or None
