"""Stamp ``src/bonsai_cc/_build_info.py`` with the git SHA at build."""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class BuildInfoHook(BuildHookInterface):
    PLUGIN_NAME = "build-info"

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        target = Path(self.root) / "src" / "bonsai_cc" / "_build_info.py"
        rev = _git_describe(self.root)
        if rev is None:
            # No git: building from a tarball. Keep any pre-baked
            # value (sdist would have stamped one in); only write
            # the fallback if nothing's there.
            if target.exists():
                return
            rev = "unknown"
        target.write_text(
            '"""Generated by hatch_build.py at build time. Do not edit."""\n'
            f"GIT_REV = {rev!r}\n",
            encoding="utf-8",
        )


def _git_describe(root: str) -> str | None:
    """``git describe --always --dirty --abbrev=7``, or None if git fails."""
    try:
        out = subprocess.check_output(
            ["git", "describe", "--always", "--dirty", "--abbrev=7"],
            cwd=root,
            stderr=subprocess.DEVNULL,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return out.strip() or None
